# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9cbb5891370933c3c50d2062a4a31962"
name = "Gleame"
handle = "Gleame"
application_url = "https://glimpse-app-charles.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "https://glimpse-app-charles.onrender.com/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_reports,read_orders"

[auth]
redirect_urls = [
  "https://glimpse-app-charles.onrender.com/auth/callback",
  "https://glimpse-app-charles.onrender.com/auth/shopify/callback",
  "https://glimpse-app-charles.onrender.com/api/auth/callback",
]

[pos]
embedded = false
