# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9cbb5891370933c3c50d2062a4a31962"
name = "glimpse-app"
handle = "glimpse-app"
application_url = "https://glimpse-app-9zjc.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://glimpse-app-9zjc.onrender.com/auth/callback",
  "https://glimpse-app-9zjc.onrender.com/auth/shopify/callback",
  "https://glimpse-app-9zjc.onrender.com/api/auth/callback",
]

[pos]
embedded = false
