-- Migration 080: v3 templates (docs/overhaul/V3-SPEC.md, V3-CONTRACTS.md §4).
--
-- Template × Look reframe: templates are decision shapes (Match, Consult,
-- Routine, Discover, Clean), Looks are token presets (Editorial, Minimal,
-- Bold). New columns are all nullable; legacy shops (quiz_template NULL)
-- never read or write them.
--
-- Run BEFORE deploying app code. Reads are defensive (missing columns
-- resolve to NULL) but the generator/studio write these columns directly.

ALTER TABLE chat_assistant_config
  ADD COLUMN IF NOT EXISTS quiz_look text,
  ADD COLUMN IF NOT EXISTS quiz_email_placement text,
  ADD COLUMN IF NOT EXISTS quiz_phases jsonb,
  ADD COLUMN IF NOT EXISTS quiz_founder jsonb,
  ADD COLUMN IF NOT EXISTS quiz_generation_report jsonb;

ALTER TABLE chat_assistant_config
  DROP CONSTRAINT IF EXISTS chat_assistant_config_quiz_look_check,
  ADD CONSTRAINT chat_assistant_config_quiz_look_check
    CHECK (quiz_look IS NULL OR quiz_look IN ('editorial', 'minimal', 'bold')),
  DROP CONSTRAINT IF EXISTS chat_assistant_config_quiz_email_placement_check,
  ADD CONSTRAINT chat_assistant_config_quiz_email_placement_check
    CHECK (quiz_email_placement IS NULL OR quiz_email_placement IN ('hook_start', 'gate_results', 'after_results', 'off'));

COMMENT ON COLUMN chat_assistant_config.quiz_look IS
  'v3: token preset applied to any template (editorial|minimal|bold). NULL = derived from the Brand Profile.';
COMMENT ON COLUMN chat_assistant_config.quiz_email_placement IS
  'v3 spec 5.2: hook_start|gate_results|after_results|off. NULL = the template default.';
COMMENT ON COLUMN chat_assistant_config.quiz_phases IS
  'v3 Match template: [{label, axisKeys[]}] grouping questions into 2-3 named phases.';
COMMENT ON COLUMN chat_assistant_config.quiz_founder IS
  'v3 Routine intro (type D): {name, credentials, portraitUrl}. NULL = intro falls to type E.';
COMMENT ON COLUMN chat_assistant_config.quiz_generation_report IS
  'v3 spec 6.5: the generation report the Studio arrival banner is assembled from. Generator-only.';

-- Brand-library indexing status (spec 4.6): indexing runs at sync; Studio
-- shows one retry banner when it failed instead of a content lock.
ALTER TABLE shops
  ADD COLUMN IF NOT EXISTS library_index_status text,
  ADD COLUMN IF NOT EXISTS library_index_error text,
  ADD COLUMN IF NOT EXISTS library_indexed_at timestamptz;

ALTER TABLE shops
  DROP CONSTRAINT IF EXISTS shops_library_index_status_check,
  ADD CONSTRAINT shops_library_index_status_check
    CHECK (library_index_status IS NULL OR library_index_status IN ('pending', 'building', 'ready', 'failed'));

-- v2 → v3 template id remap (V3-CONTRACTS §1). v2 ids meant Salon/Studio/
-- Guide/Pop/Clean; v3 ids mean Match/Consult/Routine/Discover/Clean. Only
-- rows that still carry a pre-v3 value are touched; NULL (every live
-- merchant since the 2026-09-25 incident cleanup) stays NULL.
--
-- RUN ONCE, BEFORE the v3 code deploys. The guards make a second run a
-- no-op: pre-v3 rows were last written before 2026-09-28 and have no
-- quiz_look; this UPDATE bumps updated_at so the same row can never be
-- remapped twice, and a row generated by v3 code (updated today) is
-- never touched even if migration 080 runs late. Verify first:
--   SELECT shop_domain, quiz_template, updated_at FROM chat_assistant_config WHERE quiz_template IS NOT NULL;
UPDATE chat_assistant_config
SET quiz_template = CASE quiz_template
  WHEN 't2' THEN 't1'   -- Studio (shade finder) → Match
  WHEN 't3' THEN 't2'   -- Guide (considered purchase) → Consult
  WHEN 't1' THEN 't5'   -- Salon (editorial aesthetic) → Clean; the Look carries the aesthetic
  ELSE quiz_template    -- t4 Pop → Discover, t5 → Clean
END,
    quiz_look = CASE quiz_template WHEN 't1' THEN 'editorial' WHEN 't4' THEN 'bold' ELSE NULL END,
    quiz_preset = NULL,  -- presets are retired
    updated_at = now()
WHERE quiz_template IS NOT NULL
  AND quiz_look IS NULL
  AND quiz_generation_report IS NULL
  AND updated_at < '2026-09-28T00:00:00Z';
